import { StyleSheet } from "react-native";

export default StyleSheet.create({
  /* ─── Layout ─────────────────────────────────────────── */
  container:   { flex: 1, backgroundColor: "#F8FAFC" },
  scroll:      { flex: 1, backgroundColor: "#F8FAFC" },
  content:     { paddingBottom: 40 },

  /* ─── Logo ───────────────────────────────────────────── */
  logoWrap: { alignItems: "center", marginBottom: 10 },
  logo:     { height: 90, width: 250 },

  /* ─── Header card (blue) ─────────────────────────────── */
  header: {
    backgroundColor: "#1D4ED8",
    borderRadius: 22,
    padding: 18,
    margin: 16,
    elevation: 8,
    shadowColor: "#1D4ED8",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
  },
  headerRow:   { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  roleText:    { fontSize: 10, fontWeight: "900", color: "#93C5FD", letterSpacing: 1.2, textTransform: "uppercase" },
  nameText:    { fontSize: 18, fontWeight: "900", color: "#FFF", marginTop: 2 },
  subText:     { fontSize: 11, fontWeight: "700", color: "#BFDBFE", marginTop: 2 },
  headerRight: { alignItems: "flex-end" },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  statusText:  { fontSize: 10, fontWeight: "900", color: "#FFF" },
  routeText:   { fontSize: 11, fontWeight: "800", color: "#FFF", marginTop: 8, textAlign: "right" },
  routePin:    { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 8 },

  /* ─── Section heading ────────────────────────────────── */
  sectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginHorizontal: 16,
    marginBottom: 10,
    marginTop: 4,
  },

  /* ─── Quick-action grid ──────────────────────────────── */
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  actionWrap:     { width: "48%", position: "relative" },
  action: {
    width: "100%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 15,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#F1F5F9",
    elevation: 4,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
  },
  actionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  actionText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#475569",
    textAlign: "center",
    lineHeight: 16,
  },
  actionChevron: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  badge: {
    position: "absolute",
    top: 6,
    right: 6,
    backgroundColor: "#EF4444",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    elevation: 3,
  },
  badgeText: { color: "#FFF", fontSize: 11, fontWeight: "900" },

  /* ─── Generic white card ─────────────────────────────── */
  card: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    elevation: 3,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },

  /* ─── Blue banner card (Assigned Bus) ───────────────── */
  blueCard: {
    backgroundColor: "#1E40AF",
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 16,
    overflow: "hidden",
    elevation: 6,
    shadowColor: "#1E40AF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  cardLabel:  { fontSize: 10, fontWeight: "900", color: "#94A3B8", letterSpacing: 1 },
  blueLabel:  { color: "#93C5FD" },
  cardTitle:  { fontSize: 20, fontWeight: "900", color: "#FFF", marginTop: 4 },
  cardBody:   { fontSize: 12, fontWeight: "600", color: "#DBEAFE", marginTop: 6 },
  onRoutePill:     { backgroundColor: "#10B981", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14 },
  onRoutePillText: { fontSize: 10, fontWeight: "900", color: "#FFF" },
  busWatermark:    { position: "absolute", right: -10, bottom: -14, opacity: 0.18 },

  /* ─── Transit monitor card ───────────────────────────── */
  stageIcon: {
    width: 50,
    height: 50,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  stageTitle: { fontSize: 10, fontWeight: "900", letterSpacing: 1.2, marginBottom: 2 },
  stageLabel: { fontSize: 15, fontWeight: "900", lineHeight: 18 },
  reminder: {
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    padding: 10,
    marginTop: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#EF4444",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reminderText: { fontSize: 11, fontWeight: "800", color: "#DC2626", flex: 1 },

  /* ─── Route progress card ────────────────────────────── */
  progressTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1,
    marginBottom: 20,
  },
  progressTrack: {
    position: "absolute",
    top: 19,
    left: 20,
    right: 20,
    height: 4,
    backgroundColor: "#E2E8F0",
    borderRadius: 2,
  },
  progressRow:   { flexDirection: "row", justifyContent: "space-between" },
  progressDot: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0F172A",
    shadowOpacity: 0.10,
    shadowRadius: 5,
    elevation: 3,
  },
  progressItem:     { alignItems: "center" },
  progressLabel:    { fontSize: 10, fontWeight: "900", marginTop: 8 },
  progressSubLabel: { fontSize: 9, fontWeight: "700", color: "#94A3B8", marginTop: 2 },

  /* ─── HOD stats row ──────────────────────────────────── */
  hodStats:    { flexDirection: "row", marginHorizontal: 16, marginBottom: 16, gap: 8 },
  hodStat: {
    flex: 1,
    backgroundColor: "#FFF",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  hodStatNum:   { fontSize: 22, fontWeight: "900" },
  hodStatLabel: { fontSize: 9, fontWeight: "800", color: "#64748B", marginTop: 4, textAlign: "center" },
});
