import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F3F4F6" },
  keyboard: { flex: 1 },
  container: { flex: 1, padding: 24, justifyContent: "center" },
  title: { fontSize: 24, fontWeight: "900", color: "#2563EB", textAlign: "center", lineHeight: 30 },
  titleUnderline: { height: 3, width: 120, backgroundColor: "#2563EB", alignSelf: "center", borderRadius: 2, marginTop: 10, marginBottom: 28 },
  card: { backgroundColor: "white", borderRadius: 20, padding: 20, marginBottom: 24, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  cardLabel: { fontSize: 12, fontWeight: "900", color: "#2563EB", textAlign: "center", letterSpacing: 1, marginBottom: 16 },
  roleGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  roleTile: { width: "30%", backgroundColor: "#F9FAFB", borderWidth: 1.5, borderColor: "#E5E7EB", borderRadius: 14, paddingVertical: 18, alignItems: "center", position: "relative" },
  roleTileActive: { borderColor: "#2563EB", backgroundColor: "#EFF6FF" },
  roleTileLabel: { marginTop: 6, fontSize: 12, fontWeight: "800", color: "#374151" },
  roleTileLabelActive: { color: "#2563EB" },
  checkBadge: { position: "absolute", bottom: -8, width: 18, height: 18, borderRadius: 9, backgroundColor: "#2563EB", alignItems: "center", justifyContent: "center" },
  checkBadgeText: { color: "white", fontSize: 10, fontWeight: "900" },
  inputWrap: { flexDirection: "row", alignItems: "center", backgroundColor: "white", borderWidth: 1.5, borderColor: "#E5E7EB", borderRadius: 14, paddingHorizontal: 16, height: 54, marginBottom: 14 },
  inputIcon: { fontSize: 16, marginRight: 10 },
  input: { flex: 1, fontSize: 14, fontWeight: "700", color: "#1F2937" },
  loginBtn: { backgroundColor: "#2563EB", height: 54, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 8 },
  loginBtnDisabled: { opacity: 0.7 },
  loginBtnText: { color: "white", fontSize: 15, fontWeight: "900" },
  centerFill: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32 },
  statusTitle: { fontSize: 16, fontWeight: "900", color: "#1F2937", marginTop: 16, textAlign: "center" },
  statusSubtitle: { fontSize: 12, fontWeight: "700", color: "#9CA3AF", marginTop: 6, textAlign: "center" },
  statusDetail: { fontSize: 12, color: "#DC2626", marginTop: 10, textAlign: "center" },
  statusHint: { fontSize: 11, color: "#6B7280", marginTop: 16, textAlign: "center", lineHeight: 17 },
  retryBtn: { marginTop: 24, backgroundColor: "#2563EB", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  retryBtnText: { color: "white", fontWeight: "900", fontSize: 13 },
});
