import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F3F4F6" },

  // ─────────────────────────────────────────────
  // NEW — Top App Bar
  // ─────────────────────────────────────────────
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 6,
    backgroundColor: "#FFFFFF",
  },
  menuIcon: { fontSize: 24, color: "#1F2937", fontWeight: "700" },
  topBarLogo: { width: "100%", height: 46 },
  topBarCenter: { flex: 1, alignItems: "center" },
  appTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1E3A8A",
    letterSpacing: 1,
  },
  appSubtitle: {
    fontSize: 9,
    fontWeight: "800",
    color: "#475569",
    letterSpacing: 0.5,
    marginTop: 1,
  },
  taglineBanner: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 3,
    marginTop: 4,
  },
  taglineText: {
    fontSize: 8,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.5,
  },
  bellWrap: { position: "relative", padding: 4 },
  bellIcon: { fontSize: 22 },
  bellBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: "#EF4444",
    borderRadius: 9,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  bellBadgeText: { color: "#fff", fontSize: 9, fontWeight: "900" },

  // ─────────────────────────────────────────────
  // NEW — Welcome / Duty Card
  // ─────────────────────────────────────────────
  welcomeCard: {
    backgroundColor: "#1D4ED8",
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#1D4ED8",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  welcomeAvatar: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.5)",
  },
  welcomeGreeting: {
    fontSize: 12,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "700",
  },
  welcomeName: {
    fontSize: 19,
    color: "#fff",
    fontWeight: "900",
    marginTop: 1,
    marginBottom: 4,
  },
  welcomeVehicleRow: { flexDirection: "row", alignItems: "center" },
  welcomeVehicleText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.9)",
    fontWeight: "700",
  },
  welcomeMeta: { alignItems: "flex-end", marginLeft: 8 },
  dutyPillOn: {
    backgroundColor: "#22C55E",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dutyPillOff: {
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dutyDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#fff",
  },
  dutyPillText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  dutyTime: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 8,
  },
  dutyDate: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 1,
  },

  // ─────────────────────────────────────────────
  // Home layout — fixed/non-scrollable
  // ─────────────────────────────────────────────
  homeContent: {
    flex: 1,
    minHeight: 0,
    paddingBottom: 4,
  },
  fixedBottomActions: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 6,
  },

  // ─────────────────────────────────────────────
  // Section headings / five fixed action cards
  // ─────────────────────────────────────────────
  sectionRow: {
    marginTop: 22,
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  sectionHeading: {
    fontSize: 13,
    fontWeight: "900",
    color: "#1F2937",
    letterSpacing: 0.5,
  },
  actionsRowFixed: {
    flexDirection: "row",
    paddingHorizontal: 16,
    alignItems: "stretch",
  },
  actionCard2: {
    flex: 1,
    minWidth: 0,
    height: 78,
    backgroundColor: "#fff",
    borderRadius: 13,
    paddingVertical: 8,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderBottomWidth: 3,
    overflow: "hidden",
    gap: 8,
  },
  actionCard2Icon: { fontSize: 21, marginBottom: 6 },
  actionCard2Label: {
    fontSize: 8.5,
    fontWeight: "800",
    color: "#1F2937",
    textAlign: "center",
    lineHeight: 11,
  },

  // ─────────────────────────────────────────────
  // NEW — Notifications card
  // ─────────────────────────────────────────────
  notifCard2: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 14,
    borderRadius: 16,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  notifCard2Header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  notifCard2Title: {
    fontSize: 13,
    fontWeight: "900",
    color: "#1F2937",
    letterSpacing: 0.5,
  },
  notifCard2ViewAll: {
    fontSize: 12,
    fontWeight: "800",
    color: "#2563EB",
  },
  notifRow2: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  notifIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  notifIconGlyph: { fontSize: 15, color: "#fff", fontWeight: "900" },
  notifRow2Body: { flex: 1 },
  notifRow2Title: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1F2937",
    marginBottom: 2,
  },
  notifRow2Desc: {
    fontSize: 11.5,
    color: "#6B7280",
    fontWeight: "500",
    lineHeight: 16,
  },
  notifRow2Time: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "700",
    marginLeft: 8,
  },
  notifEmptyText: {
    fontSize: 12,
    color: "#9CA3AF",
    textAlign: "center",
    paddingVertical: 16,
  },

  // ─────────────────────────────────────────────
  // NEW — Big scan button + SOS row
  // ─────────────────────────────────────────────
  scanBigBtn: {
    marginHorizontal: 0,
    marginTop: 0,
    backgroundColor: "#16A34A",
    borderRadius: 16,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#16A34A",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  scanBigBtnIcon: { fontSize: 18, marginRight: 10, color: "#fff" },
  scanBigBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginLeft: 10
  },
  sosRow2: {
    marginHorizontal: 0,
    marginTop: 7,
    marginBottom: 0,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#FECACA",
  },
  sosBadgeBox: {
    borderWidth: 1.5,
    borderColor: "#EF4444",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginRight: 12,
  },
  sosBadgeText: { color: "#EF4444", fontSize: 10, fontWeight: "900" },
  sosRow2Body: { flex: 1 },
  sosRow2Title: { fontSize: 13, fontWeight: "900", color: "#1F2937" },
  sosRow2Desc: { fontSize: 11, color: "#6B7280", fontWeight: "600", marginTop: 1 },
  sosCallCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  sosCallGlyph: { fontSize: 16 },

  homeHdr: {
    minHeight: 70,
    backgroundColor: "#2563EB",
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingTop: 15,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  profileImgWrap: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.4)",
    marginRight: 12,
  },
  hdrMainInfo: { flex: 1, justifyContent: "center" },
  hdrCatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  hdrRole: {
    fontSize: 9,
    color: "rgba(255,255,255,0.7)",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  hdrName: { fontSize: 16, fontWeight: "800", color: "#fff", marginTop: 2 },
  hdrStatusPill: {
    fontSize: 9,
    fontWeight: "800",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
    overflow: "hidden",
  },

  dashboard: { flexDirection: "row", padding: 15, flex: 1 },
  actionColumn: { width: 135, paddingRight: 10 },
  actionBtn: {
    backgroundColor: "white",
    borderColor: "#E5E7EB",
    borderWidth: 1.5,
    borderRadius: 12,
    height: 75,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    padding: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  actionBtnText: {
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    color: "#374151",
    textTransform: "uppercase",
  },
  notifColumn: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    padding: 8,
  },
  notifTitle: {
    fontSize: 11,
    color: "#9CA3AF",
    fontWeight: "800",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  notifTile: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  notifText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 8,
    lineHeight: 14,
  },
  notifBtns: { flexDirection: "row", gap: 8 },
  smallBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  btnBlue: { backgroundColor: "#2563EB" },
  btnGray: { backgroundColor: "#F3F4F6" },
  smallBtnText: { color: "white", fontSize: 10, fontWeight: "800" },
  bottomArea: { padding: 12 },
  tripStatusCard: {
    backgroundColor: "#E2E8F0",
    padding: 10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  tripLabel: { fontSize: 10, color: "#6B7280", fontWeight: "800" },
  tripValue: { fontSize: 13, color: "#1F2937", fontWeight: "800" },
  closeTripBtn: {
    backgroundColor: "#EF4444",
    padding: 14,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  btnMainText: { color: "white", fontSize: 14, fontWeight: "800" },
  sosBtn: {
    backgroundColor: "white",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#F3F4F6",
    alignItems: "center",
  },
  sosText: { color: "#374151", fontSize: 13, fontWeight: "800" },
  sosIcon: {
    color: "#EF4444",
    borderWidth: 1.5,
    borderColor: "#EF4444",
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  cameraContainer: { flex: 1, backgroundColor: "black" },
  camera: { flex: 1 },
  cameraFrame: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  cameraTitle: {
    position: "absolute",
    top: 50,
    color: "white",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    width: "100%",
    zIndex: 10,
  },
  wrapperQR: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 20,
  },
  wrapperFace: {
    width: 280,
    height: 350,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
    borderRadius: 20,
    borderStyle: "dashed",
  },
  cameraHint: { color: "white", marginTop: 20, fontWeight: "bold" },
  cameraControls: {
    position: "absolute",
    bottom: 50,
    width: "100%",
    alignItems: "center",
  },
  shutter: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 5,
    borderColor: "white",
    padding: 4,
  },
  shutterInner: { flex: 1, backgroundColor: "white", borderRadius: 35 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 30,
  },
  issueCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 30,
    alignItems: "center",
  },
  modalTitle: { fontSize: 18, fontWeight: "900", color: "#1F2937" },
  issueGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "100%",
  },
  issueTile: {
    width: "48%",
    backgroundColor: "#F9FAFB",
    padding: 15,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  issueTileLabel: { fontSize: 11, fontWeight: "800", marginTop: 8 },
  cancelText: { color: "#6B7280", fontWeight: "bold", marginTop: 10 },

  // HOD Styles
  sectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#6B7280",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  statsGrid: { flexDirection: "row", gap: 12, marginBottom: 15 },
  statCard: {
    flex: 1,
    backgroundColor: "white",
    padding: 15,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  statVal: { fontSize: 22, fontWeight: "900", color: "#1F2937" },
  statLab: { fontSize: 10, color: "#6B7280", fontWeight: "600", marginTop: 2 },
  reasonRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  pillText: { fontSize: 10, fontWeight: "800", color: "white" },
  absenteeTile: {
    backgroundColor: "white",
    marginHorizontal: 15,
    marginBottom: 10,
    padding: 15,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#7C3AED",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  absName: { fontSize: 14, fontWeight: "800", color: "#1F2937" },
  absId: { fontSize: 10, color: "#9CA3AF", fontWeight: "600" },
  absBus: { fontSize: 11, color: "#6B7280", marginTop: 2, fontWeight: "600" },
  absReason: { fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
  absStatus: { fontSize: 10, color: "#9CA3AF", fontWeight: "700" },
  callBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  vehicleTrackCard: {
    backgroundColor: "white",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  vNum: { fontSize: 13, fontWeight: "800", color: "#1F2937" },
  vDetail: { fontSize: 10, color: "#6B7280", marginTop: 2 },
  vStatusPill: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  vStatusText: { fontSize: 9, fontWeight: "900" },
  modalHdr: {
    minHeight: 70,
    backgroundColor: "#2563EB",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalCloseText: { color: "white", fontWeight: "900", fontSize: 12 },
  blueHeader: {
    backgroundColor: "#2563EB",
    paddingHorizontal: 20,
    justifyContent: "center",
  },
});

export const profileStyles = StyleSheet.create({
  avatarRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#EFF6FF",
    borderWidth: 4,
    borderColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: "#2563EB",
    letterSpacing: 0.5,
    marginBottom: 14,
  },
  row: { flexDirection: "row" },
  col: { flex: 1 },
  label: {
    fontSize: 10,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  value: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0F172A",
  },
});