import { StyleSheet } from "react-native";

export const maintStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F3F4F6" },
  staffHeader: {
    backgroundColor: "#0F766E",
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 14,
  },
  staffAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.4)",
  },
  staffLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  staffName: { color: "#fff", fontSize: 18, fontWeight: "900", marginTop: 2 },
  staffEmp: { color: "rgba(255,255,255,0.75)", fontSize: 11, fontWeight: "700", marginTop: 2 },
  logoutPill: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  rowActionBtn: {
    backgroundColor: "#2563EB",
    margin: 14,
    marginBottom: 6,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#374151",
    letterSpacing: 0.5,
  },
  emptyText: {
    fontSize: 12,
    color: "#9CA3AF",
    textAlign: "center",
    paddingVertical: 14,
  },
  issueCard: {
    marginHorizontal: 14,
    marginBottom: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    padding: 14,
  },
  issueCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  severityPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  severityPillText: { color: "#fff", fontSize: 9, fontWeight: "900" },
  issueMeta: { fontSize: 10, color: "#6B7280", fontWeight: "700", marginBottom: 4 },
  issueTitle: { fontSize: 13, fontWeight: "800", color: "#1F2937", marginBottom: 6 },
  issueTag: { fontSize: 10, color: "#6B7280", fontWeight: "700", marginBottom: 10 },
  ackBtn: {
    backgroundColor: "#EF4444",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
  },
  taskCard: {
    marginHorizontal: 14,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  taskTitle: { fontSize: 13, fontWeight: "800", color: "#1F2937" },
  taskSub: { fontSize: 10, color: "#6B7280", fontWeight: "600", marginTop: 3 },
  taskStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 80,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#0F766E",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  resolvedNote: {
    fontSize: 11,
    fontWeight: "700",
    color: "#059669",
    marginTop: 2,
  },
});
